name: Accuknox SAST

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Run Accuknox SAST: Opengrep"
        uses: accuknox/sast-scan-opengrep-action@1.0.0
        with:
          accuknox_endpoint: "cspm.sda.mindsparks.io"
          accuknox_tenant: "${{ secrets.TENANT_ID }}"
          accuknox_token: "${{ secrets.ACCUKNOX_TOKEN }}"
          accuknox_label: "DVWA"
          input_soft_fail: "true"
          upload_artifact: false
